create database ISUIT;
USE ISUIT;
CREATE TABLE DATOS_USUARIO(TP_USUARIO VARCHAR(15) PRIMARY KEY,
FECHANAC DATE,
NOMBRE VARCHAR(20),
APELLIDOP VARCHAR(20),
CORREO VARCHAR(100) UNIQUE,
CONTRASEÑA VARCHAR(100) UNIQUE,
NOMBRE_USUARIO);

CREATE TABLE DATOPRODUCTO(ID_PRODUCTO VARCHAR(30) PRIMARY KEY,
TIPO VARCHAR (20),
NOMBRE VARCHAR(30),
PRECIO FLOAT,
CANTIDAD_P INTEGER,
ORIGEN VARCHAR(20),
DESCRIPCION VARCHAR(500));

CREATE TABLE COMPRA(ID_COMPRA VARCHAR(30) UNIQUE,
NOMBRE_US VARCHAR()30,
DOMICILIO VARCHAR(50),
DIA_ENTREGA DATE,
ID_PRODUCTO VARCHAR(30),
FOREIGN KEY (NOMBRE_US) REFERENCES DATOS_USUARIO(NOMBRE_USURIO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES DATOPRODUCTO(ID_PRODUCTO));